# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fighter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('fights', models.IntegerField()),
                ('strikes', models.IntegerField()),
                ('strike_accuracy', models.FloatField()),
                ('takedowns', models.IntegerField()),
                ('takedown_accuracy', models.FloatField()),
                ('knockdowns', models.IntegerField()),
                ('passes', models.IntegerField()),
                ('reversals', models.IntegerField()),
                ('submissions', models.IntegerField()),
            ],
        ),
    ]
